FROM ubuntu
RUN apt update
# Build
RUN apt install -y build-essential make git vim
# Python
RUN apt install -y python python3 python3-pip
# Network
RUN apt install -y iputils-ping net-tools curl dnsutils
# Utils
RUN apt install -y tmux unzip vim software-properties-common htop man
# SSH
RUN apt install -y openssh-client openssh-server
# Terminal
RUN apt install -y tmux screen 
RUN cd / && git clone https://github.com/nodejs/node
WORKDIR /node
RUN ./configure
CMD tail -f